[control_plane]
k8s-control01 ansible_host=10.1.93.50

[workers]
k8s-worker01 ansible_host=10.1.93.51
k8s-worker02 ansible_host=10.1.93.52

[database]
db01 ansible_host=10.1.93.53

[monitoring]
monitor01 ansible_host=10.1.93.54

[load_balancer]
lb01 ansible_host=10.1.93.55

[backup]
backup01 ansible_host=10.1.93.56

[deploy_runners]
runner01 ansible_host=10.1.93.57

[development]
fds-dev-01 ansible_host=10.1.93.58

[kubernetes:children]
control_plane
workers

[all:vars]
ansible_user=fdsadmin
ansible_become=true
